services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/logs
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=star_wars_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=star_wars_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 
